# Generated by Django 3.1.2 on 2020-10-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherM',
            new_name='WeatherModel',
        ),
    ]
